#pragma once

// Wokwi's simulated Wi-Fi network — open network, no password
#define WIFI_SSID "Wokwi-GUEST"
#define WIFI_PASSWORD ""

// Your AWS IoT endpoint from Phase 4
#define AWS_IOT_ENDPOINT "a1jg5cptbrzoqy-ats.iot.us-east-1.amazonaws.com"

// Must exactly match the Thing name you created in Phase 4
#define THING_NAME "mfa-token-simulator"

// MQTT topics
#define MQTT_PUB_TOPIC "mfa/otp"
#define MQTT_SUB_TOPIC "mfa/result"

// Amazon Root CA 1
static const char AWS_CERT_CA[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----
)EOF";

// Device certificate (f5a6c799...b0dea0-certificate.pem.crt)
static const char AWS_CERT_CRT[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDWTCCAkGgAwIBAgIUZnoWI2uoNhsCdlq95em047+crqAwDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTI2MDkwNDExNTg0
NloXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0
ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMp72cI70wJLZxEvKaLS
/wvEEoVVdcY7om95gG3cqo4JCCAgEm2jK1RURuZku3tlWXDa3KOTNA8ylzHhP+Ly
dMIUWyKGfsk8oPG78RRigA7LKhJhd6ezScOkK1qmA+JB9QkU9Lq8zwZdWVkuLeJy
+8UP1TDDzKrZFWEChZ0m8IlNdehJuy7nw9z0EV26VCN8F+VbdEUkroNjGJEDfFut
HfgvdCIwlT2d0Zd8DXGCTWzHvR8iC8BfUiyWCzKQndeZVgAwttwp1ERROSzwBSzI
wslVGV/cYYkN16IVQNfuIaX/QDbDoy2lvhTQ3tIe8bHni+8ZkzEHxK0ARHAuB/6o
L7MCAwEAAaNgMF4wHwYDVR0jBBgwFoAUM2qfphqVHUgXEuwa8eNbFDgeuRYwHQYD
VR0OBBYEFJ+n23KT3g31vZkUQfUQWWdcjAjOMAwGA1UdEwEB/wQCMAAwDgYDVR0P
AQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQA1OUfEENe/rqcxZm1UWU3kaovb
yYLI2Q9Qm3/i78zzJP0dtWesrMks4u+yFDHxoMney2sSJA/bITiLy9fWbU13CFhZ
Aonh9avuSed6vUzFdRGeGw8n80moX7N/nL7GxJP9OWKi7UtS0SPDps1Yes5EaPTW
Eq43wp6gNQJy20mH1DMEiMm8hYxngSLbjbh/qj0GxhYK8EEn2y3DG1QPe4nwhULb
NfpX2c5Oxd4uFfMGChNZUpeecm/KhHdKu53koZMwUlAko59m7mZpSWWYOhfhB2i5
GYYrSbHtaBFhX1KVOA2IzUqinMRajsfljLcO6LlnhfV91LGzc7nzsBc3Lu8K
-----END CERTIFICATE-----
)EOF";

// ---- PASTE YOUR PRIVATE KEY BELOW ----
// Open f5a6c799c448add5b60afd401c7f0ff8183332d91dc8a9a4b2084dd828b0dea0-private.pem.key
// in Notepad, select all, copy, and paste it in place of the two placeholder lines below.
// Keep the R"EOF( ... )EOF" wrapper exactly as-is.
static const char AWS_CERT_PRIVATE[] PROGMEM = R"EOF(
-----BEGIN RSA PRIVATE KEY-----
PASTE THE CONTENTS OF YOUR PRIVATE KEY (.pem.key) HERE
-----END RSA PRIVATE KEY-----
)EOF";